import "aos/dist/aos.css";
import "swiper/css";
import "swiper/css/effect-cards";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import "../../../core/styles/index.scss";

import "../public/globals.css";

import JourneyForm from "../../../core/components/footer/form/JourneyForm";
import localFont from "next/font/local";
import { Footer } from "../../../core/components/footer/Footer";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { Providers } from "../../../core/components/Providers";
import Header1 from "../../../core/template/header/header-3";

const helvetica = localFont({
  src: "../../../../public/fonts/helvetica-light.ttf",
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

if (typeof window !== "undefined") {
  require("bootstrap/dist/js/bootstrap");
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = useMessages();

  const authenticated = true;

  return (
    <html lang={locale}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Jost:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favico.svg" />
        <title>Exotic</title>
      </head>
      <body className={helvetica.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>
            <Header1 />
            {children}
            <JourneyForm></JourneyForm>
            <Footer />
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
