export const destinations4 = [
    {
        id: 1,
        img: "/img/destinations/3/1.png",
        location: "London, UK",
        properties: "4,090",
        delayAnimation: "0",
    },
    {
        id: 2,
        img: "/img/destinations/3/2.png",
        location: "Edinburg, UK",
        properties: "4,090",
        delayAnimation: "100",
    },
    {
        id: 3,
        img: "/img/destinations/3/3.png",
        location: "France",
        properties: "4,090",
        delayAnimation: "200",
    },
    {
        id: 4,
        img: "/img/destinations/3/4.png",
        location: "Turkey",
        properties: "4,090",
        delayAnimation: "300",
    },
    {
        id: 5,
        img: "/img/destinations/3/5.png",
        location: "Spain",
        properties: "4,090",
        delayAnimation: "400",
    },
    {
        id: 6,
        img: "/img/destinations/3/1.png",
        location: "United Kingdom",
        properties: "4,090",
        delayAnimation: "500",
    },
    {
        id: 7,
        img: "/img/destinations/3/2.png",
        location: "Italy",
        properties: "4,090",
        delayAnimation: "600",
    },
    {
        id: 8,
        img: "/img/destinations/3/3.png",
        location: "France",
        properties: "4,090",
        delayAnimation: "700",
    },
    {
        id: 9,
        img: "/img/destinations/3/1.png",
        location: "London, UK",
        properties: "4,090",
        delayAnimation: "800",
    },
    {
        id: 10,
        img: "/img/destinations/3/2.png",
        location: "Edinburg, UK",
        properties: "4,090",
        delayAnimation: "900",
    },
];